# Generated by Django 4.0.3 on 2022-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='work_info',
            field=models.CharField(blank=True, max_length=512, verbose_name='工作信息'),
        ),
    ]
